# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: zhgchgli
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "GroovyGrouper's Links"

# Avatar image path
avatar: "./images/profile.webp"

# Name section text
name: "@GroovyGrouper"

# Tagline section text
tagline: >-
    Relatable content for Relators.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-TikTok"
      text: "TikTok"
      url: "https://www.tiktok.com/@groovygrouper"
      alt: "TikTok"
      title: "TikTok"
      target: "_blank"
  - link:
      icon: "fa-brands fa-Twitch"
      text: "Twitch"
      url: "https://www.twitch.tv/groovygrouper"
      alt: "Twitch"
      title: "Twitch"
      target: "_blank"
  - link:
      icon: "fa-brands fa-twitter"
      text: "X <span class='link-button-text'>({{vars.MediumFollowersCountPlugin}} Followers)</span>"
      url: "https://x.com/groovygrouper"
      alt: "X / Twitter"
      title: "X / Twitter"
      target: "_blank"
  - link:
      icon: "fa-brands fa-youtube"
      text: "YouTube"
      url: "https://www.youtube.com/groovygrouper"
      alt: "YouTube"
      title: "YouTube"
      target: "_blank"



#   - link:
#       icon: "fa-brands fa-swift"
#       text: "ZMarkupParser <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/ZMarkupParser']}} Stars)</span>"
#       url: "https://github.com/ZhgChgLi/ZMarkupParser"
#       alt: "ZMarkupParser is a pure-Swift library that helps you to convert HTML strings to NSAttributedString with customized style and tags."
#       title: "ZMarkupParser is a pure-Swift library that helps you to convert HTML strings to NSAttributedString with customized style and tags."
#       target: "_blank"
#   - link:
#       icon: "fa-brands fa-app-store-ios"
#       text: "ZReviewTender <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/ZReviewTender']}} Stars)</span>"
#       url: "https://github.com/ZhgChgLi/ZReviewTender"
#       alt: "ZReviewTender is a tool for fetching app reviews from the App Store and Google Play Console and integrating them into your workflow."
#       title: "ZReviewTender is a tool for fetching app reviews from the App Store and Google Play Console and integrating them into your workflow."
#       target: "_blank"
#   - link:
#       icon: "fa-brands fa-markdown"
#       text: "ZMediumToMarkdown <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/ZMediumToMarkdown']}} Stars)</span>"
#       url: "https://github.com/ZhgChgLi/ZMediumToMarkdown"
#       alt: "ZMediumToMarkdown is a powerful tool that allows you to effortlessly download and convert your Medium posts to Markdown format."
#       title: "ZMediumToMarkdown is a powerful tool that allows you to effortlessly download and convert your Medium posts to Markdown format."
#       target: "_blank"
#   - link:
#       icon: "fa-brands fa-github"
#       text: "linkyee <span class='link-button-text'>({{vars.GithubRepoStarsCountPlugin['ZhgChgLi/linkyee']}} Stars)</span>"
#       url: "https://github.com/ZhgChgLi/linkyee"
#       alt: "linkyee is a fully customized, open-source LinkTree alternative deployed directly on GitHub Pages."
#       title: "linkyee is a fully customized, open-source LinkTree alternative deployed directly on GitHub Pages."
#       target: "_blank"


# List of social media links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# title: The url title
# url: The URL of the social media link
# alt: Alternative text for accessibility
# target: _blank opens in a new tab, _self opens in the same frame
socials:
  - social:
      icon: "fa-brands fa-tiktok"
      url: "https://www.tiktok.com/@groovygrouper"
      title: "TikTok"
      alt: "GroovyGrouper's TikTok"
      target: "_blank"
  - social:
      icon: "fa-brands fa-twitch"
      url: "https://www.twitch.tv/groovygrouper"
      title: "Twitch"
      alt: "GroovyGrouper's Twitch"
      target: "_blank"
  - social:
      icon: "fa-brands fa-twitter"
      url: "https://x.com/groovygrouper"
      title: "Twitter"
      alt: "GroovyGrouper's Twitter"
      target: "_blank"
  - social:
      icon: "fa-brands fa-youtube"
      url: "https://www.youtube.com/groovygrouper"
      title: "YouTube"
      alt: "GroovyGrouper's YouTube"
      target: "_blank"
#   - social:
#       icon: "fa-solid fa-envelope"
#       url: "mailto:zhgchgli@gmail.com"
#       title: "Email: zhgchgli@gmail.com"
#       alt: "zhgchgli@gmail.com"
#       target: "_blank"

# Footer text
footer: >
    If you're reading this, you're a true relator.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2024  <a href="https://www.groovygrouper.com" target="_blank">GroovyGrouper</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
